apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-lb
spec:
  type: LoadBalancer
  selector:
    app: mario
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
