apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-deployment
  labels:
    app: mario
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
        - name: mario
          image: pengbai/docker-supermario:latest
          ports:
            - containerPort: 8080
